languageCode = "en"
languageName = "English"
displayName = "EN"
isoCode = "en"
weight = 1
rtl = false

title = "nymark.cloud"
#logo = "img/favicon-32x32.png"
description = "Blog"
# copyright = "Copy, _right?_ :thinking_face:"

dateFormat = "2 January 2006"

[author]
  name = "Raymond Nymark"
  image = "img/cloud_logo.png"
  headline = "Cloud Developer"
  bio = ""
links = [
{ linkedin = "https://linkedin.com/in/raymondnymark" },
{ twitter = "https://twitter.com/Nattie__0" }
]
